// ── HOMOPHONES ──
const homophoneQuestions = [
    // ─── a / à ───
    { sentence: "Il ___ un chien très gentil.", answer: "a", choices: ["a","à"], explanation: "« a » = verbe avoir (il a). On peut remplacer par « avait »." },
    { sentence: "Elle va ___ l'école tous les matins.", answer: "à", choices: ["a","à"], explanation: "« à » = préposition (indique le lieu). On ne peut pas dire « avait l'école »." },
    { sentence: "Mon frère ___ oublié son cartable.", answer: "a", choices: ["a","à"], explanation: "« a » = verbe avoir. On peut dire « avait oublié »." },
    { sentence: "Je pense ___ mes vacances.", answer: "à", choices: ["a","à"], explanation: "« à » = préposition. On ne peut pas remplacer par « avait »." },
    { sentence: "La maîtresse ___ distribué les cahiers.", answer: "a", choices: ["a","à"], explanation: "« a » = verbe avoir (elle a distribué)." },
    { sentence: "Nous irons ___ la piscine demain.", answer: "à", choices: ["a","à"], explanation: "« à » = préposition de lieu." },
    { sentence: "Papa ___ réparé le vélo.", answer: "a", choices: ["a","à"], explanation: "« a » = verbe avoir. On peut dire « avait réparé »." },
    { sentence: "Le gâteau est ___ la vanille.", answer: "à", choices: ["a","à"], explanation: "« à » = préposition (saveur). On ne peut pas dire « avait la vanille »." },
    { sentence: "Le directeur ___ parlé aux élèves.", answer: "a", choices: ["a","à"], explanation: "« a » = verbe avoir (il a parlé)." },
    { sentence: "Elle joue ___ la corde ___ sauter.", answer: "à", choices: ["a","à"], explanation: "« à » = préposition. On ne peut pas remplacer par « avait »." },
    { sentence: "Ce film ___ l'air très drôle.", answer: "a", choices: ["a","à"], explanation: "« a » = verbe avoir (avoir l'air). On peut dire « avait l'air »." },
    { sentence: "Grâce ___ toi, on a gagné !", answer: "à", choices: ["a","à"], explanation: "« à » = préposition. « Grâce avait toi » ne veut rien dire." },
    { sentence: "Ma cousine ___ sept ans.", answer: "a", choices: ["a","à"], explanation: "« a » = verbe avoir (elle a sept ans)." },
    { sentence: "Nous habitons ___ Paris.", answer: "à", choices: ["a","à"], explanation: "« à » = préposition de lieu." },
    { sentence: "Le chat ___ attrapé une souris.", answer: "a", choices: ["a","à"], explanation: "« a » = verbe avoir. On peut dire « avait attrapé »." },
    { sentence: "Il commence ___ pleuvoir.", answer: "à", choices: ["a","à"], explanation: "« à » = préposition (commencer à). On ne dit pas « avait pleuvoir »." },

    // ─── et / est ───
    { sentence: "Le chat ___ noir et blanc.", answer: "est", choices: ["et","est"], explanation: "« est » = verbe être. On peut dire « était »." },
    { sentence: "J'ai acheté du pain ___ du beurre.", answer: "et", choices: ["et","est"], explanation: "« et » = conjonction (ajoute deux choses). On peut dire « et puis »." },
    { sentence: "Ma sœur ___ partie en voyage.", answer: "est", choices: ["et","est"], explanation: "« est » = verbe être (elle est partie)." },
    { sentence: "Il aime les pommes ___ les poires.", answer: "et", choices: ["et","est"], explanation: "« et » relie deux compléments. On peut dire « et aussi »." },
    { sentence: "Cette histoire ___ très amusante.", answer: "est", choices: ["et","est"], explanation: "« est » = verbe être. On peut dire « était »." },
    { sentence: "Prends ton manteau ___ tes gants.", answer: "et", choices: ["et","est"], explanation: "« et » = conjonction qui relie deux noms." },
    { sentence: "Mon voisin ___ très sympathique.", answer: "est", choices: ["et","est"], explanation: "« est » = verbe être. On peut dire « était sympathique »." },
    { sentence: "J'ai un cahier ___ un crayon.", answer: "et", choices: ["et","est"], explanation: "« et » = conjonction. On peut dire « et aussi un crayon »." },
    { sentence: "Le temps ___ magnifique aujourd'hui.", answer: "est", choices: ["et","est"], explanation: "« est » = verbe être. On peut dire « était magnifique »." },
    { sentence: "Range tes livres ___ tes crayons.", answer: "et", choices: ["et","est"], explanation: "« et » relie deux compléments d'objet." },
    { sentence: "Ce restaurant ___ fermé le lundi.", answer: "est", choices: ["et","est"], explanation: "« est » = verbe être. On peut dire « était fermé »." },
    { sentence: "Il fait beau ___ chaud.", answer: "et", choices: ["et","est"], explanation: "« et » relie deux adjectifs." },
    { sentence: "La récréation ___ bientôt terminée.", answer: "est", choices: ["et","est"], explanation: "« est » = verbe être. On peut dire « était terminée »." },
    { sentence: "Léa mange une tartine ___ boit un jus.", answer: "et", choices: ["et","est"], explanation: "« et » relie deux actions. On peut dire « et puis boit »." },

    // ─── son / sont ───
    { sentence: "Les enfants ___ dans la cour.", answer: "sont", choices: ["son","sont"], explanation: "« sont » = verbe être (ils sont). On peut dire « étaient »." },
    { sentence: "Il a perdu ___ stylo.", answer: "son", choices: ["son","sont"], explanation: "« son » = déterminant possessif (le sien). On peut dire « mon stylo »." },
    { sentence: "Ces gâteaux ___ délicieux.", answer: "sont", choices: ["son","sont"], explanation: "« sont » = verbe être. On peut dire « étaient délicieux »." },
    { sentence: "Elle adore ___ petit chat.", answer: "son", choices: ["son","sont"], explanation: "« son » = déterminant possessif. On peut dire « mon petit chat »." },
    { sentence: "Les oiseaux ___ partis vers le sud.", answer: "sont", choices: ["son","sont"], explanation: "« sont » = verbe être (ils sont partis)." },
    { sentence: "Léo range ___ bureau.", answer: "son", choices: ["son","sont"], explanation: "« son » = déterminant possessif. On peut dire « mon bureau »." },
    { sentence: "Les magasins ___ ouverts le samedi.", answer: "sont", choices: ["son","sont"], explanation: "« sont » = verbe être. On peut dire « étaient ouverts »." },
    { sentence: "Il a oublié ___ goûter.", answer: "son", choices: ["son","sont"], explanation: "« son » = déterminant possessif. On peut dire « mon goûter »." },
    { sentence: "Les résultats ___ affichés au tableau.", answer: "sont", choices: ["son","sont"], explanation: "« sont » = verbe être. On peut dire « étaient affichés »." },
    { sentence: "Lucie lit ___ livre préféré.", answer: "son", choices: ["son","sont"], explanation: "« son » = déterminant possessif. On peut dire « mon livre »." },
    { sentence: "Ces exercices ___ faciles.", answer: "sont", choices: ["son","sont"], explanation: "« sont » = verbe être. On peut dire « étaient faciles »." },
    { sentence: "Il promène ___ chien tous les soirs.", answer: "son", choices: ["son","sont"], explanation: "« son » = déterminant possessif. On peut dire « mon chien »." },

    // ─── on / ont ───
    { sentence: "___ mange à la cantine aujourd'hui.", answer: "On", choices: ["On","Ont"], explanation: "« On » = pronom (= quelqu'un / nous). On peut dire « il mange »." },
    { sentence: "Les élèves ___ fini leur exercice.", answer: "ont", choices: ["on","ont"], explanation: "« ont » = verbe avoir (ils ont). On peut dire « avaient fini »." },
    { sentence: "___ a bien rigolé pendant la récréation.", answer: "On", choices: ["On","Ont"], explanation: "« On » = pronom sujet. On peut remplacer par « il »." },
    { sentence: "Mes parents ___ préparé une surprise.", answer: "ont", choices: ["on","ont"], explanation: "« ont » = verbe avoir (ils ont). On peut dire « avaient préparé »." },
    { sentence: "___ dirait qu'il va pleuvoir.", answer: "On", choices: ["On","Ont"], explanation: "« On » = pronom sujet. On peut dire « il dirait »." },
    { sentence: "Les voisins ___ déménagé.", answer: "ont", choices: ["on","ont"], explanation: "« ont » = verbe avoir (ils ont). On peut dire « avaient déménagé »." },
    { sentence: "___ part en vacances la semaine prochaine.", answer: "On", choices: ["On","Ont"], explanation: "« On » = pronom sujet. On peut dire « il part »." },
    { sentence: "Les joueurs ___ marqué trois buts.", answer: "ont", choices: ["on","ont"], explanation: "« ont » = verbe avoir. On peut dire « avaient marqué »." },
    { sentence: "___ ne sait pas encore le résultat.", answer: "On", choices: ["On","Ont"], explanation: "« On » = pronom sujet (= nous / quelqu'un)." },
    { sentence: "Ils ___ trouvé un trésor dans le jardin.", answer: "ont", choices: ["on","ont"], explanation: "« ont » = verbe avoir. On peut dire « avaient trouvé »." },

    // ─── ou / où ───
    { sentence: "Tu préfères le rouge ___ le bleu ?", answer: "ou", choices: ["ou","où"], explanation: "« ou » = conjonction de choix. On peut dire « ou bien »." },
    { sentence: "La ville ___ j'habite est très jolie.", answer: "où", choices: ["ou","où"], explanation: "« où » indique un lieu. On ne peut pas dire « ou bien j'habite »." },
    { sentence: "Veux-tu du jus ___ de l'eau ?", answer: "ou", choices: ["ou","où"], explanation: "« ou » = choix entre deux choses. On peut dire « ou bien »." },
    { sentence: "C'est l'endroit ___ nous avons pique-niqué.", answer: "où", choices: ["ou","où"], explanation: "« où » = pronom relatif de lieu." },
    { sentence: "On joue dehors ___ dedans ?", answer: "ou", choices: ["ou","où"], explanation: "« ou » = choix. On peut dire « ou bien dedans »." },
    { sentence: "Le jour ___ je suis né, il neigeait.", answer: "où", choices: ["ou","où"], explanation: "« où » indique un moment dans le temps." },
    { sentence: "Tu viens lundi ___ mardi ?", answer: "ou", choices: ["ou","où"], explanation: "« ou » = choix entre deux jours. On peut dire « ou bien »." },
    { sentence: "Montre-moi ___ tu as rangé mes clés.", answer: "où", choices: ["ou","où"], explanation: "« où » = pronom interrogatif de lieu." },
    { sentence: "C'est un film comique ___ dramatique ?", answer: "ou", choices: ["ou","où"], explanation: "« ou » = choix. On peut dire « ou bien dramatique »." },
    { sentence: "La maison ___ habitait ma grand-mère est très vieille.", answer: "où", choices: ["ou","où"], explanation: "« où » = pronom relatif de lieu." },

    // ─── ce / se ───
    { sentence: "___ matin, il fait très froid.", answer: "Ce", choices: ["Ce","Se"], explanation: "« Ce » = déterminant démonstratif devant un nom (ce matin)." },
    { sentence: "Le chat ___ cache sous le lit.", answer: "se", choices: ["ce","se"], explanation: "« se » = pronom réfléchi devant un verbe (se cacher)." },
    { sentence: "___ livre est passionnant.", answer: "Ce", choices: ["Ce","Se"], explanation: "« Ce » = déterminant démonstratif (ce livre = celui-là)." },
    { sentence: "Les enfants ___ lavent les mains.", answer: "se", choices: ["ce","se"], explanation: "« se » = pronom réfléchi (se laver)." },
    { sentence: "___ film m'a beaucoup plu.", answer: "Ce", choices: ["Ce","Se"], explanation: "« Ce » = déterminant démonstratif (ce film)." },
    { sentence: "Marie ___ brosse les dents.", answer: "se", choices: ["ce","se"], explanation: "« se » = pronom réfléchi (se brosser)." },
    { sentence: "___ gâteau est vraiment bon.", answer: "Ce", choices: ["Ce","Se"], explanation: "« Ce » = déterminant démonstratif (ce gâteau)." },
    { sentence: "Le soleil ___ couche derrière la montagne.", answer: "se", choices: ["ce","se"], explanation: "« se » = pronom réfléchi (se coucher)." },
    { sentence: "___ soir, on regarde un film.", answer: "Ce", choices: ["Ce","Se"], explanation: "« Ce » = déterminant démonstratif devant un nom (ce soir)." },
    { sentence: "Ils ___ regardent dans le miroir.", answer: "se", choices: ["ce","se"], explanation: "« se » = pronom réfléchi (se regarder)." },
    { sentence: "___ problème est difficile.", answer: "Ce", choices: ["Ce","Se"], explanation: "« Ce » = déterminant démonstratif (ce problème)." },
    { sentence: "Le bébé ___ réveille en pleurant.", answer: "se", choices: ["ce","se"], explanation: "« se » = pronom réfléchi (se réveiller)." },

    // ─── ces / ses ───
    { sentence: "Il a rangé ___ affaires dans son sac.", answer: "ses", choices: ["ces","ses"], explanation: "« ses » = possessif (les siennes). On peut dire « mes affaires »." },
    { sentence: "Regarde ___ fleurs magnifiques !", answer: "ces", choices: ["ces","ses"], explanation: "« ces » = démonstratif (celles-là). On peut dire « cette fleur »." },
    { sentence: "Elle a perdu ___ lunettes.", answer: "ses", choices: ["ces","ses"], explanation: "« ses » = possessif (les siennes). On peut dire « mes lunettes »." },
    { sentence: "___ arbres sont très grands.", answer: "Ces", choices: ["Ces","Ses"], explanation: "« Ces » = démonstratif (ceux-là). On peut dire « cet arbre »." },
    { sentence: "Lucas a invité ___ amis pour son anniversaire.", answer: "ses", choices: ["ces","ses"], explanation: "« ses » = possessif (les siens). On peut dire « mes amis »." },
    { sentence: "Qui a construit ___ immeubles ?", answer: "ces", choices: ["ces","ses"], explanation: "« ces » = démonstratif (ceux-là, qu'on montre)." },
    { sentence: "Elle enfile ___ chaussures neuves.", answer: "ses", choices: ["ces","ses"], explanation: "« ses » = possessif (les siennes). On peut dire « mes chaussures »." },
    { sentence: "___ nuages annoncent la pluie.", answer: "Ces", choices: ["Ces","Ses"], explanation: "« Ces » = démonstratif (ceux qu'on voit)." },

    // ─── c'est / s'est ───
    { sentence: "___ mon meilleur ami.", answer: "C'est", choices: ["C'est","S'est"], explanation: "« C'est » = cela est. On présente quelqu'un ou quelque chose." },
    { sentence: "Il ___ trompé de chemin.", answer: "s'est", choices: ["c'est","s'est"], explanation: "« s'est » = pronom réfléchi + être (se tromper → il s'est trompé)." },
    { sentence: "___ une bonne idée !", answer: "C'est", choices: ["C'est","S'est"], explanation: "« C'est » = cela est. On peut dire « c'était une bonne idée »." },
    { sentence: "Le vase ___ cassé en tombant.", answer: "s'est", choices: ["c'est","s'est"], explanation: "« s'est » = se casser → il s'est cassé." },
    { sentence: "___ la plus belle journée de l'année.", answer: "C'est", choices: ["C'est","S'est"], explanation: "« C'est » = cela est." },
    { sentence: "Ma sœur ___ endormie sur le canapé.", answer: "s'est", choices: ["c'est","s'est"], explanation: "« s'est » = s'endormir → elle s'est endormie." },
    { sentence: "___ bientôt les vacances !", answer: "C'est", choices: ["C'est","S'est"], explanation: "« C'est » = cela est." },
    { sentence: "Le chat ___ griffé en jouant.", answer: "s'est", choices: ["c'est","s'est"], explanation: "« s'est » = se griffer → il s'est griffé." },

    // ─── leur / leurs ───
    { sentence: "Je ___ ai donné des bonbons.", answer: "leur", choices: ["leur","leurs"], explanation: "« leur » devant un verbe = pronom (= à eux). Invariable." },
    { sentence: "Les enfants rangent ___ jouets.", answer: "leurs", choices: ["leur","leurs"], explanation: "« leurs » devant un nom pluriel = déterminant possessif." },
    { sentence: "Il ___ explique la leçon.", answer: "leur", choices: ["leur","leurs"], explanation: "« leur » devant un verbe = pronom. Pas de « s »." },
    { sentence: "Ils ont apporté ___ cahiers.", answer: "leurs", choices: ["leur","leurs"], explanation: "« leurs » devant un nom pluriel = possessif pluriel." },
    { sentence: "La maîtresse ___ lit une histoire.", answer: "leur", choices: ["leur","leurs"], explanation: "« leur » devant un verbe = pronom (= à eux)." },
    { sentence: "Elles ont oublié ___ parapluie.", answer: "leur", choices: ["leur","leurs"], explanation: "« leur » devant un nom singulier = possessif singulier (un seul parapluie chacune)." },

    // ─── la / l'a / là ───
    { sentence: "Je ___ vois tous les jours.", answer: "la", choices: ["la","l'a","là"], explanation: "« la » = pronom COD (je vois qui ? → la)." },
    { sentence: "Il ___ appelée ce matin.", answer: "l'a", choices: ["la","l'a","là"], explanation: "« l'a » = l' + a (verbe avoir). Il l'avait appelée." },
    { sentence: "Pose ton sac ___.", answer: "là", choices: ["la","l'a","là"], explanation: "« là » = adverbe de lieu (= ici)." },
    { sentence: "Ma mère ___ accompagnée à l'école.", answer: "l'a", choices: ["la","l'a","là"], explanation: "« l'a » = l' + a (verbe avoir). On peut dire « l'avait accompagnée »." },
    { sentence: "___ fenêtre est ouverte.", answer: "La", choices: ["La","L'a","Là"], explanation: "« La » = déterminant (article défini féminin)." },
    { sentence: "C'est ___ qu'on se retrouve.", answer: "là", choices: ["la","l'a","là"], explanation: "« là » = adverbe de lieu." },

    // ─── quel / quelle / qu'elle ───
    { sentence: "___ heure est-il ?", answer: "Quelle", choices: ["Quel","Quelle","Qu'elle"], explanation: "« Quelle » = déterminant interrogatif féminin (l'heure est féminin)." },
    { sentence: "Je sais ___ viendra demain.", answer: "qu'elle", choices: ["quel","quelle","qu'elle"], explanation: "« qu'elle » = que + elle. Je sais que elle viendra." },
    { sentence: "___ beau temps !", answer: "Quel", choices: ["Quel","Quelle","Qu'elle"], explanation: "« Quel » = déterminant exclamatif masculin (le temps est masculin)." },
    { sentence: "Il pense ___ a raison.", answer: "qu'elle", choices: ["quel","quelle","qu'elle"], explanation: "« qu'elle » = que + elle. Il pense que elle a raison." },
    { sentence: "___ surprise !", answer: "Quelle", choices: ["Quel","Quelle","Qu'elle"], explanation: "« Quelle » = déterminant exclamatif féminin (la surprise)." },
    { sentence: "___ est ton sport préféré ?", answer: "Quel", choices: ["Quel","Quelle","Qu'elle"], explanation: "« Quel » = déterminant interrogatif masculin (le sport)." },

    // ─── mais / mes ───
    { sentence: "J'aime le chocolat ___ pas la vanille.", answer: "mais", choices: ["mais","mes"], explanation: "« mais » = conjonction d'opposition. On peut dire « cependant »." },
    { sentence: "J'ai oublié ___ clés à la maison.", answer: "mes", choices: ["mais","mes"], explanation: "« mes » = déterminant possessif (les miennes)." },
    { sentence: "Il fait froid ___ il y a du soleil.", answer: "mais", choices: ["mais","mes"], explanation: "« mais » = conjonction d'opposition." },
    { sentence: "___ amis sont venus me voir.", answer: "Mes", choices: ["Mais","Mes"], explanation: "« Mes » = déterminant possessif pluriel." },
    { sentence: "J'aimerais venir ___ je ne peux pas.", answer: "mais", choices: ["mais","mes"], explanation: "« mais » = opposition. On peut dire « pourtant »." },
    { sentence: "Je range ___ affaires dans le placard.", answer: "mes", choices: ["mais","mes"], explanation: "« mes » = déterminant possessif (les miennes)." },
];
