// ── DROITES ──
const droitesQuestions = [
    { question: "Que sont deux droites parallèles ?", answer: "Deux droites qui ne se croisent jamais", choices: ["Deux droites qui ne se croisent jamais", "Deux droites qui se croisent à angle droit", "Deux droites qui se coupent en un point", "Deux droites de même longueur"], explanation: "Des droites parallèles gardent toujours le même écart : elles ne se croisent jamais." },
    { question: "Que sont deux droites perpendiculaires ?", answer: "Deux droites qui se croisent en formant un angle droit", choices: ["Deux droites qui se croisent en formant un angle droit", "Deux droites qui ne se croisent jamais", "Deux droites de même longueur", "Deux droites courbes"], explanation: "Deux droites perpendiculaires forment un angle de 90° (angle droit) à leur point d'intersection." },
    { question: "Que sont deux droites sécantes ?", answer: "Deux droites qui se croisent en un point", choices: ["Deux droites qui se croisent en un point", "Deux droites qui ne se croisent jamais", "Deux droites superposées", "Deux droites parallèles"], explanation: "Deux droites sécantes se coupent en exactement un point. Les droites perpendiculaires sont des sécantes particulières." },
    { question: "Quel instrument permet de vérifier qu'un angle est droit ?", answer: "L'équerre", choices: ["L'équerre", "Le compas", "Le rapporteur", "La règle"], explanation: "L'équerre possède un angle droit qui permet de vérifier la perpendicularité." },
    { question: "Qu'est-ce qu'une droite ?", answer: "Une ligne infinie et parfaitement droite", choices: ["Une ligne infinie et parfaitement droite", "Un segment avec deux extrémités", "Une ligne courbe", "Un trait qui commence à un point"], explanation: "Une droite est illimitée des deux côtés, contrairement au segment qui a deux extrémités." },
    { question: "Qu'est-ce qu'un segment ?", answer: "Une portion de droite limitée par deux points", choices: ["Une portion de droite limitée par deux points", "Une droite infinie", "Un trait qui part d'un point sans fin", "Une ligne courbe"], explanation: "Un segment est une partie de droite délimitée par deux extrémités." },
    { question: "Qu'est-ce qu'une demi-droite ?", answer: "Une droite qui a un point de départ mais pas de fin", choices: ["Une droite qui a un point de départ mais pas de fin", "La moitié d'un segment", "Deux droites parallèles", "Un segment très court"], explanation: "Une demi-droite part d'un point (origine) et se prolonge à l'infini dans une direction." },
    { question: "Si deux droites sont parallèles à une même troisième droite, alors :", answer: "Elles sont parallèles entre elles", choices: ["Elles sont parallèles entre elles", "Elles sont perpendiculaires entre elles", "Elles se croisent", "On ne peut pas savoir"], explanation: "Si d₁ // d₃ et d₂ // d₃, alors d₁ // d₂. C'est une propriété des droites parallèles." },
    { question: "Quel symbole utilise-t-on pour noter que deux droites sont parallèles ?", answer: "//", choices: ["//", "⊥", "=", "≠"], explanation: "Le symbole // signifie « est parallèle à ». Par exemple (d₁) // (d₂)." },
    { question: "Quel symbole utilise-t-on pour noter que deux droites sont perpendiculaires ?", answer: "⊥", choices: ["⊥", "//", "=", "×"], explanation: "Le symbole ⊥ signifie « est perpendiculaire à ». Par exemple (d₁) ⊥ (d₂)." },
    { question: "Deux droites perpendiculaires sont-elles sécantes ?", answer: "Oui, toujours", choices: ["Oui, toujours", "Non, jamais", "Seulement parfois", "Ce sont des droites parallèles"], explanation: "Les droites perpendiculaires se croisent en formant un angle droit : elles sont donc toujours sécantes." },
    { question: "Si deux droites sont perpendiculaires à une même troisième droite, alors :", answer: "Elles sont parallèles entre elles", choices: ["Elles sont parallèles entre elles", "Elles sont perpendiculaires entre elles", "Elles se croisent forcément", "On ne peut pas savoir"], explanation: "Si d₁ ⊥ d₃ et d₂ ⊥ d₃, alors d₁ // d₂." },
];
