// ── FIGURES ──
const figuresQuestions = [
    { question: "Combien de côtés a un triangle ?", answer: "3", choices: ["3", "4", "5", "6"], explanation: "Un triangle a toujours 3 côtés, 3 sommets et 3 angles." },
    { question: "Comment appelle-t-on un triangle qui a ses trois côtés de même longueur ?", answer: "Un triangle équilatéral", choices: ["Un triangle équilatéral", "Un triangle isocèle", "Un triangle rectangle", "Un triangle scalène"], explanation: "Équilatéral signifie « côtés égaux ». Ses 3 angles mesurent chacun 60°." },
    { question: "Comment appelle-t-on un triangle qui a deux côtés de même longueur ?", answer: "Un triangle isocèle", choices: ["Un triangle isocèle", "Un triangle équilatéral", "Un triangle rectangle", "Un triangle scalène"], explanation: "Un triangle isocèle a exactement deux côtés égaux et deux angles égaux." },
    { question: "Comment appelle-t-on un triangle qui a un angle droit ?", answer: "Un triangle rectangle", choices: ["Un triangle rectangle", "Un triangle équilatéral", "Un triangle isocèle", "Un triangle obtusangle"], explanation: "Un triangle rectangle possède un angle de 90° (angle droit)." },
    { question: "Combien de côtés a un quadrilatère ?", answer: "4", choices: ["3", "4", "5", "6"], explanation: "Quad signifie « quatre » : un quadrilatère a 4 côtés." },
    { question: "Qu'est-ce qui caractérise un carré ?", answer: "4 côtés égaux et 4 angles droits", choices: ["4 côtés égaux et 4 angles droits", "4 côtés égaux seulement", "4 angles droits seulement", "2 paires de côtés parallèles"], explanation: "Le carré cumule deux propriétés : 4 côtés de même longueur ET 4 angles droits." },
    { question: "Qu'est-ce qui caractérise un rectangle ?", answer: "4 angles droits et côtés opposés égaux", choices: ["4 angles droits et côtés opposés égaux", "4 côtés égaux", "Seulement 2 angles droits", "Des diagonales perpendiculaires"], explanation: "Le rectangle a 4 angles droits. Ses côtés opposés sont parallèles et de même longueur." },
    { question: "Qu'est-ce qu'un losange ?", answer: "Un quadrilatère avec 4 côtés de même longueur", choices: ["Un quadrilatère avec 4 côtés de même longueur", "Un rectangle penché", "Un quadrilatère avec 4 angles droits", "Un triangle allongé"], explanation: "Le losange a 4 côtés égaux mais ses angles ne sont pas forcément droits (sinon ce serait un carré)." },
    { question: "Qu'est-ce qu'un parallélogramme ?", answer: "Un quadrilatère avec les côtés opposés parallèles", choices: ["Un quadrilatère avec les côtés opposés parallèles", "Un quadrilatère avec 4 côtés égaux", "Un triangle avec 4 sommets", "Un quadrilatère avec un seul angle droit"], explanation: "Dans un parallélogramme, les côtés opposés sont parallèles deux à deux et de même longueur." },
    { question: "Combien de côtés a un hexagone ?", answer: "6", choices: ["5", "6", "7", "8"], explanation: "Hexa signifie « six ». Un hexagone a 6 côtés." },
    { question: "Combien de côtés a un pentagone ?", answer: "5", choices: ["4", "5", "6", "7"], explanation: "Penta signifie « cinq ». Un pentagone a 5 côtés." },
    { question: "Comment appelle-t-on une figure qui a tous ses côtés et tous ses angles égaux ?", answer: "Un polygone régulier", choices: ["Un polygone régulier", "Un polygone irrégulier", "Un rectangle", "Un cercle"], explanation: "Un polygone régulier a tous ses côtés de même longueur et tous ses angles de même mesure." },
    { question: "Le carré est-il un rectangle ?", answer: "Oui", choices: ["Oui", "Non", "Seulement parfois", "Ce sont des figures différentes"], explanation: "Oui ! Le carré est un rectangle particulier dont les 4 côtés sont égaux." },
    { question: "Le carré est-il un losange ?", answer: "Oui", choices: ["Oui", "Non", "Seulement parfois", "Ce sont des figures différentes"], explanation: "Oui ! Le carré est un losange particulier dont les 4 angles sont droits." },
    { question: "Comment appelle-t-on un quadrilatère qui a exactement une paire de côtés parallèles ?", answer: "Un trapèze", choices: ["Un trapèze", "Un parallélogramme", "Un losange", "Un rectangle"], explanation: "Le trapèze a exactement une paire de côtés parallèles (les « bases »)." },
];
