// ── CONJUGAISON ──
const conjugaisonQuestions = [
    // ─── Présent ───
    { level: "ce2", sentence: "Nous ___ (manger) à midi.", answer: "mangeons", hint: "manger – présent – nous", explanation: "Manger au présent avec « nous » → mangeons." },
    { level: "ce2", sentence: "Tu ___ (finir) tes devoirs.", answer: "finis", hint: "finir – présent – tu", explanation: "Finir au présent avec « tu » → finis." },
    { level: "ce2", sentence: "Les oiseaux ___ (chanter) dans les arbres.", answer: "chantent", hint: "chanter – présent – ils", explanation: "Chanter au présent avec « ils » → chantent." },
    { level: "ce2", sentence: "Je ___ (prendre) le bus chaque matin.", answer: "prends", hint: "prendre – présent – je", explanation: "Prendre au présent avec « je » → prends." },
    { level: "ce2", sentence: "Vous ___ (aller) au marché le samedi.", answer: "allez", hint: "aller – présent – vous", explanation: "Aller au présent avec « vous » → allez." },
    { level: "ce2", sentence: "Elle ___ (être) très contente.", answer: "est", hint: "être – présent – elle", explanation: "Être au présent avec « elle » → est." },
    { level: "ce2", sentence: "Nous ___ (avoir) un contrôle demain.", answer: "avons", hint: "avoir – présent – nous", explanation: "Avoir au présent avec « nous » → avons." },
    { level: "ce2", sentence: "Tu ___ (venir) avec moi ?", answer: "viens", hint: "venir – présent – tu", explanation: "Venir au présent avec « tu » → viens." },
    { level: "ce2", sentence: "Je ___ (dire) la vérité.", answer: "dis", hint: "dire – présent – je", explanation: "Dire au présent avec « je » → dis." },
    { level: "ce2", sentence: "Nous ___ (écrire) une lettre.", answer: "écrivons", hint: "écrire – présent – nous", explanation: "Écrire au présent avec « nous » → écrivons." },
    { level: "ce2", sentence: "Vous ___ (faire) du sport le mercredi.", answer: "faites", hint: "faire – présent – vous", explanation: "Faire au présent avec « vous » → faites." },
    { level: "ce2", sentence: "Il ___ (savoir) nager.", answer: "sait", hint: "savoir – présent – il", explanation: "Savoir au présent avec « il » → sait." },
    { level: "ce2", sentence: "Les enfants ___ (grandir) vite.", answer: "grandissent", hint: "grandir – présent – ils", explanation: "Grandir au présent avec « ils » → grandissent (2e groupe : -issent)." },
    { level: "ce2", sentence: "Tu ___ (pouvoir) m'aider ?", answer: "peux", hint: "pouvoir – présent – tu", explanation: "Pouvoir au présent avec « tu » → peux." },
    { level: "ce2", sentence: "Je ___ (voir) le sommet de la montagne.", answer: "vois", hint: "voir – présent – je", explanation: "Voir au présent avec « je » → vois." },
    { level: "ce2", sentence: "Nous ___ (choisir) un livre à la bibliothèque.", answer: "choisissons", hint: "choisir – présent – nous", explanation: "Choisir au présent avec « nous » → choisissons (2e groupe)." },
    { level: "ce2", sentence: "Vous ___ (vouloir) du dessert ?", answer: "voulez", hint: "vouloir – présent – vous", explanation: "Vouloir au présent avec « vous » → voulez." },
    { level: "ce2", sentence: "Elle ___ (mettre) son manteau.", answer: "met", hint: "mettre – présent – elle", explanation: "Mettre au présent avec « elle » → met." },
    { level: "ce2", sentence: "Les chats ___ (dormir) beaucoup.", answer: "dorment", hint: "dormir – présent – ils", explanation: "Dormir au présent avec « ils » → dorment." },
    { level: "ce2", sentence: "Tu ___ (lire) un roman passionnant.", answer: "lis", hint: "lire – présent – tu", explanation: "Lire au présent avec « tu » → lis." },
    { level: "ce2", sentence: "Je ___ (devoir) me dépêcher.", answer: "dois", hint: "devoir – présent – je", explanation: "Devoir au présent avec « je » → dois." },
    { level: "ce2", sentence: "Nous ___ (courir) dans le parc.", answer: "courons", hint: "courir – présent – nous", explanation: "Courir au présent avec « nous » → courons." },
    { level: "ce2", sentence: "Vous ___ (apprendre) le français.", answer: "apprenez", hint: "apprendre – présent – vous", explanation: "Apprendre au présent avec « vous » → apprenez." },
    { level: "ce2", sentence: "Elles ___ (partir) en vacances.", answer: "partent", hint: "partir – présent – elles", explanation: "Partir au présent avec « elles » → partent." },
    { level: "ce2", sentence: "Je ___ (croire) en toi.", answer: "crois", hint: "croire – présent – je", explanation: "Croire au présent avec « je » → crois." },
    { level: "ce2", sentence: "Il ___ (peindre) un tableau.", answer: "peint", hint: "peindre – présent – il", explanation: "Peindre au présent avec « il » → peint." },
    { level: "ce2", sentence: "Tu ___ (sortir) ce soir ?", answer: "sors", hint: "sortir – présent – tu", explanation: "Sortir au présent avec « tu » → sors." },
    { level: "ce2", sentence: "Nous ___ (boire) de l'eau fraîche.", answer: "buvons", hint: "boire – présent – nous", explanation: "Boire au présent avec « nous » → buvons." },
    { level: "ce2", sentence: "Vous ___ (connaître) cette chanson ?", answer: "connaissez", hint: "connaître – présent – vous", explanation: "Connaître au présent avec « vous » → connaissez." },
    { level: "ce2", sentence: "Les poules ___ (pondre) des œufs.", answer: "pondent", hint: "pondre – présent – elles", explanation: "Pondre au présent avec « elles » → pondent." },

    // ─── Imparfait ───
    { level: "cm1", sentence: "Avant, je ___ (jouer) dans le jardin.", answer: "jouais", hint: "jouer – imparfait – je", explanation: "Jouer à l'imparfait avec « je » → jouais." },
    { level: "cm1", sentence: "Nous ___ (faire) du vélo tous les jours.", answer: "faisions", hint: "faire – imparfait – nous", explanation: "Faire à l'imparfait avec « nous » → faisions." },
    { level: "cm1", sentence: "Tu ___ (être) en CE2 l'an dernier.", answer: "étais", hint: "être – imparfait – tu", explanation: "Être à l'imparfait avec « tu » → étais." },
    { level: "cm1", sentence: "Les enfants ___ (courir) dans la cour.", answer: "couraient", hint: "courir – imparfait – ils", explanation: "Courir à l'imparfait avec « ils » → couraient." },
    { level: "cm1", sentence: "Elle ___ (avoir) un chat roux.", answer: "avait", hint: "avoir – imparfait – elle", explanation: "Avoir à l'imparfait avec « elle » → avait." },
    { level: "cm1", sentence: "Vous ___ (partir) toujours en avance.", answer: "partiez", hint: "partir – imparfait – vous", explanation: "Partir à l'imparfait avec « vous » → partiez." },
    { level: "cm1", sentence: "Il ___ (pleuvoir) tous les après-midi.", answer: "pleuvait", hint: "pleuvoir – imparfait – il", explanation: "Pleuvoir à l'imparfait → il pleuvait." },
    { level: "cm1", sentence: "Nous ___ (aller) à la mer chaque été.", answer: "allions", hint: "aller – imparfait – nous", explanation: "Aller à l'imparfait avec « nous » → allions." },
    { level: "cm1", sentence: "Tu ___ (vouloir) un vélo rouge.", answer: "voulais", hint: "vouloir – imparfait – tu", explanation: "Vouloir à l'imparfait avec « tu » → voulais." },
    { level: "cm1", sentence: "Les voisins ___ (chanter) le soir.", answer: "chantaient", hint: "chanter – imparfait – ils", explanation: "Chanter à l'imparfait avec « ils » → chantaient." },
    { level: "cm1", sentence: "Je ___ (lire) des bandes dessinées.", answer: "lisais", hint: "lire – imparfait – je", explanation: "Lire à l'imparfait avec « je » → lisais." },
    { level: "cm1", sentence: "Vous ___ (manger) toujours ensemble.", answer: "mangiez", hint: "manger – imparfait – vous", explanation: "Manger à l'imparfait avec « vous » → mangiez." },
    { level: "cm1", sentence: "Ma grand-mère ___ (préparer) des crêpes.", answer: "préparait", hint: "préparer – imparfait – elle", explanation: "Préparer à l'imparfait avec « elle » → préparait." },
    { level: "cm1", sentence: "On ___ (voir) les étoiles la nuit.", answer: "voyait", hint: "voir – imparfait – on", explanation: "Voir à l'imparfait avec « on » → voyait." },
    { level: "cm1", sentence: "Nous ___ (finir) nos devoirs avant le dîner.", answer: "finissions", hint: "finir – imparfait – nous", explanation: "Finir à l'imparfait avec « nous » → finissions (2e groupe)." },
    { level: "cm1", sentence: "Tu ___ (prendre) le train chaque matin.", answer: "prenais", hint: "prendre – imparfait – tu", explanation: "Prendre à l'imparfait avec « tu » → prenais." },
    { level: "cm1", sentence: "Les élèves ___ (écrire) dans leur cahier.", answer: "écrivaient", hint: "écrire – imparfait – ils", explanation: "Écrire à l'imparfait avec « ils » → écrivaient." },
    { level: "cm1", sentence: "Je ___ (savoir) cette leçon par cœur.", answer: "savais", hint: "savoir – imparfait – je", explanation: "Savoir à l'imparfait avec « je » → savais." },
    { level: "cm1", sentence: "Vous ___ (dire) toujours bonjour.", answer: "disiez", hint: "dire – imparfait – vous", explanation: "Dire à l'imparfait avec « vous » → disiez." },
    { level: "cm1", sentence: "Elle ___ (mettre) une robe bleue.", answer: "mettait", hint: "mettre – imparfait – elle", explanation: "Mettre à l'imparfait avec « elle » → mettait." },

    // ─── Futur ───
    { level: "cm1", sentence: "Demain, il ___ (pleuvoir).", answer: "pleuvra", hint: "pleuvoir – futur – il", explanation: "Pleuvoir au futur → il pleuvra." },
    { level: "cm1", sentence: "Nous ___ (visiter) le musée la semaine prochaine.", answer: "visiterons", hint: "visiter – futur – nous", explanation: "Visiter au futur avec « nous » → visiterons." },
    { level: "cm1", sentence: "Tu ___ (pouvoir) venir demain.", answer: "pourras", hint: "pouvoir – futur – tu", explanation: "Pouvoir au futur avec « tu » → pourras." },
    { level: "cm1", sentence: "Elles ___ (danser) au spectacle de l'école.", answer: "danseront", hint: "danser – futur – elles", explanation: "Danser au futur avec « elles » → danseront." },
    { level: "cm1", sentence: "Je ___ (voir) mes grands-parents ce week-end.", answer: "verrai", hint: "voir – futur – je", explanation: "Voir au futur avec « je » → verrai." },
    { level: "cm1", sentence: "Vous ___ (devoir) réviser pour le contrôle.", answer: "devrez", hint: "devoir – futur – vous", explanation: "Devoir au futur avec « vous » → devrez." },
    { level: "cm1", sentence: "Il ___ (faire) beau demain.", answer: "fera", hint: "faire – futur – il", explanation: "Faire au futur avec « il » → fera." },
    { level: "cm1", sentence: "Nous ___ (être) en vacances bientôt.", answer: "serons", hint: "être – futur – nous", explanation: "Être au futur avec « nous » → serons." },
    { level: "cm1", sentence: "Tu ___ (avoir) dix ans en juin.", answer: "auras", hint: "avoir – futur – tu", explanation: "Avoir au futur avec « tu » → auras." },
    { level: "cm1", sentence: "Je ___ (venir) te chercher à la gare.", answer: "viendrai", hint: "venir – futur – je", explanation: "Venir au futur avec « je » → viendrai." },
    { level: "cm1", sentence: "Les enfants ___ (grandir) et deviendront grands.", answer: "grandiront", hint: "grandir – futur – ils", explanation: "Grandir au futur avec « ils » → grandiront." },
    { level: "cm1", sentence: "Vous ___ (aller) au cinéma samedi.", answer: "irez", hint: "aller – futur – vous", explanation: "Aller au futur avec « vous » → irez." },
    { level: "cm1", sentence: "Elle ___ (savoir) la réponse demain.", answer: "saura", hint: "savoir – futur – elle", explanation: "Savoir au futur avec « elle » → saura." },
    { level: "cm1", sentence: "Nous ___ (courir) le marathon en mai.", answer: "courrons", hint: "courir – futur – nous", explanation: "Courir au futur avec « nous » → courrons (deux r !)." },
    { level: "cm1", sentence: "Tu ___ (envoyer) la lettre demain.", answer: "enverras", hint: "envoyer – futur – tu", explanation: "Envoyer au futur avec « tu » → enverras." },
    { level: "cm1", sentence: "Je ___ (mettre) mon plus beau costume.", answer: "mettrai", hint: "mettre – futur – je", explanation: "Mettre au futur avec « je » → mettrai." },
    { level: "cm1", sentence: "Ils ___ (prendre) l'avion pour la première fois.", answer: "prendront", hint: "prendre – futur – ils", explanation: "Prendre au futur avec « ils » → prendront." },
    { level: "cm1", sentence: "Vous ___ (écrire) une rédaction.", answer: "écrirez", hint: "écrire – futur – vous", explanation: "Écrire au futur avec « vous » → écrirez." },
    { level: "cm1", sentence: "Elle ___ (vouloir) sûrement venir.", answer: "voudra", hint: "vouloir – futur – elle", explanation: "Vouloir au futur avec « elle » → voudra." },
    { level: "cm1", sentence: "On ___ (manger) des crêpes à la Chandeleur.", answer: "mangera", hint: "manger – futur – on", explanation: "Manger au futur avec « on » → mangera." },

    // ─── Passé composé ───
    { level: "cm2", sentence: "J'___ (manger) une pomme.", answer: "ai mangé", hint: "manger – passé composé – je", explanation: "Manger au passé composé avec « je » → j'ai mangé." },
    { level: "cm2", sentence: "Elle ___ (partir) à huit heures.", answer: "est partie", hint: "partir – passé composé – elle", explanation: "Partir au passé composé avec « elle » → est partie (auxiliaire être)." },
    { level: "cm2", sentence: "Nous ___ (finir) nos devoirs.", answer: "avons fini", hint: "finir – passé composé – nous", explanation: "Finir au passé composé avec « nous » → avons fini." },
    { level: "cm2", sentence: "Ils ___ (aller) au cinéma.", answer: "sont allés", hint: "aller – passé composé – ils", explanation: "Aller au passé composé avec « ils » → sont allés (auxiliaire être)." },
    { level: "cm2", sentence: "Tu ___ (prendre) ton petit-déjeuner ?", answer: "as pris", hint: "prendre – passé composé – tu", explanation: "Prendre au passé composé avec « tu » → as pris." },
    { level: "cm2", sentence: "Elle ___ (tomber) dans la cour.", answer: "est tombée", hint: "tomber – passé composé – elle", explanation: "Tomber au passé composé avec « elle » → est tombée (auxiliaire être)." },
    { level: "cm2", sentence: "Nous ___ (voir) un arc-en-ciel.", answer: "avons vu", hint: "voir – passé composé – nous", explanation: "Voir au passé composé avec « nous » → avons vu." },
    { level: "cm2", sentence: "Vous ___ (écrire) une lettre.", answer: "avez écrit", hint: "écrire – passé composé – vous", explanation: "Écrire au passé composé avec « vous » → avez écrit." },
    { level: "cm2", sentence: "J'___ (venir) dès que possible.", answer: "suis venu", hint: "venir – passé composé – je", explanation: "Venir au passé composé avec « je » → suis venu (auxiliaire être)." },
    { level: "cm2", sentence: "Les filles ___ (arriver) en retard.", answer: "sont arrivées", hint: "arriver – passé composé – elles", explanation: "Arriver au passé composé avec « elles » → sont arrivées (auxiliaire être, fém. pluriel)." },
    { level: "cm2", sentence: "Il ___ (lire) ce livre en une journée.", answer: "a lu", hint: "lire – passé composé – il", explanation: "Lire au passé composé avec « il » → a lu." },
    { level: "cm2", sentence: "Tu ___ (faire) un beau dessin.", answer: "as fait", hint: "faire – passé composé – tu", explanation: "Faire au passé composé avec « tu » → as fait." },
    { level: "cm2", sentence: "Nous ___ (dire) la vérité.", answer: "avons dit", hint: "dire – passé composé – nous", explanation: "Dire au passé composé avec « nous » → avons dit." },
    { level: "cm2", sentence: "Elles ___ (descendre) au rez-de-chaussée.", answer: "sont descendues", hint: "descendre – passé composé – elles", explanation: "Descendre au passé composé avec « elles » → sont descendues (auxiliaire être)." },
    { level: "cm2", sentence: "J'___ (mettre) la table.", answer: "ai mis", hint: "mettre – passé composé – je", explanation: "Mettre au passé composé avec « je » → ai mis." },
    { level: "cm2", sentence: "Vous ___ (pouvoir) résoudre le problème.", answer: "avez pu", hint: "pouvoir – passé composé – vous", explanation: "Pouvoir au passé composé avec « vous » → avez pu." },

    // ─── Passé simple ───
    { level: "cm2", sentence: "Il ___ (marcher) pendant des heures.", answer: "marcha", hint: "marcher – passé simple – il", explanation: "Marcher au passé simple avec « il » → marcha (1er groupe : -a)." },
    { level: "cm2", sentence: "Ils ___ (finir) leur repas en silence.", answer: "finirent", hint: "finir – passé simple – ils", explanation: "Finir au passé simple avec « ils » → finirent (2e groupe : -irent)." },
    { level: "cm2", sentence: "Elle ___ (prendre) la fuite.", answer: "prit", hint: "prendre – passé simple – elle", explanation: "Prendre au passé simple avec « elle » → prit." },
    { level: "cm2", sentence: "Le roi ___ (faire) construire un château.", answer: "fit", hint: "faire – passé simple – il", explanation: "Faire au passé simple avec « il » → fit." },
    { level: "cm2", sentence: "Les soldats ___ (partir) à l'aube.", answer: "partirent", hint: "partir – passé simple – ils", explanation: "Partir au passé simple avec « ils » → partirent." },
    { level: "cm2", sentence: "Je ___ (voir) une étoile filante.", answer: "vis", hint: "voir – passé simple – je", explanation: "Voir au passé simple avec « je » → vis." },
    { level: "cm2", sentence: "Elle ___ (être) surprise par la nouvelle.", answer: "fut", hint: "être – passé simple – elle", explanation: "Être au passé simple avec « elle » → fut." },
    { level: "cm2", sentence: "Il ___ (avoir) une idée géniale.", answer: "eut", hint: "avoir – passé simple – il", explanation: "Avoir au passé simple avec « il » → eut." },
    { level: "cm2", sentence: "Ils ___ (dire) adieu et partirent.", answer: "dirent", hint: "dire – passé simple – ils", explanation: "Dire au passé simple avec « ils » → dirent." },
    { level: "cm2", sentence: "Le chevalier ___ (venir) au secours de la princesse.", answer: "vint", hint: "venir – passé simple – il", explanation: "Venir au passé simple avec « il » → vint." },
];
