// ── LE CERCLE ──
const cercleQuestions = [
    { level: "ce2", question: "Comment appelle-t-on un segment qui relie le centre d'un cercle à un point du cercle ?", answer: "Le rayon", choices: ["Le rayon", "Le diamètre", "La corde", "L'arc"], explanation: "Le rayon est le segment qui va du centre à n'importe quel point sur le cercle." },
    { level: "ce2", question: "Comment appelle-t-on un segment qui relie deux points du cercle en passant par le centre ?", answer: "Le diamètre", choices: ["Le rayon", "Le diamètre", "La corde", "La tangente"], explanation: "Le diamètre passe par le centre et relie deux points du cercle. Il mesure le double du rayon." },
    { level: "cm1", question: "Qu'est-ce qu'une corde d'un cercle ?", answer: "Un segment reliant deux points du cercle", choices: ["Un segment reliant deux points du cercle", "Un segment passant par le centre", "Une droite qui touche le cercle en un point", "La moitié du diamètre"], explanation: "Une corde relie deux points du cercle. Le diamètre est une corde particulière qui passe par le centre." },
    { level: "ce2", question: "Quel est le rapport entre le diamètre et le rayon ?", answer: "Le diamètre = 2 × le rayon", choices: ["Le diamètre = 2 × le rayon", "Le diamètre = le rayon ÷ 2", "Le diamètre = le rayon + 2", "Le diamètre = le rayon"], explanation: "Le diamètre est toujours égal à deux fois le rayon (d = 2r)." },
    { level: "cm1", question: "Comment appelle-t-on une portion du cercle située entre deux points ?", answer: "Un arc de cercle", choices: ["Un arc de cercle", "Une corde", "Un rayon", "Un secteur"], explanation: "L'arc de cercle est la partie de la ligne courbe du cercle entre deux points." },
    { level: "cm1", question: "Qu'est-ce qu'un disque ?", answer: "La surface intérieure d'un cercle", choices: ["La surface intérieure d'un cercle", "Le contour du cercle", "Un cercle sans centre", "Un demi-cercle"], explanation: "Le disque est la surface délimitée par le cercle. Le cercle est seulement la ligne courbe." },
    { level: "ce2", question: "Comment appelle-t-on le point à égale distance de tous les points du cercle ?", answer: "Le centre", choices: ["Le centre", "Le sommet", "Le milieu", "Le foyer"], explanation: "Le centre est le point depuis lequel tous les points du cercle sont à la même distance (le rayon)." },
    { level: "ce2", question: "Si le rayon d'un cercle mesure 5 cm, combien mesure le diamètre ?", answer: "10 cm", choices: ["10 cm", "5 cm", "2,5 cm", "15 cm"], explanation: "Le diamètre = 2 × rayon = 2 × 5 = 10 cm." },
    { level: "ce2", question: "Si le diamètre d'un cercle mesure 12 cm, combien mesure le rayon ?", answer: "6 cm", choices: ["6 cm", "12 cm", "24 cm", "3 cm"], explanation: "Le rayon = diamètre ÷ 2 = 12 ÷ 2 = 6 cm." },
    { level: "ce2", question: "Quel instrument utilise-t-on pour tracer un cercle ?", answer: "Un compas", choices: ["Un compas", "Une règle", "Une équerre", "Un rapporteur"], explanation: "Le compas permet de tracer un cercle en gardant une distance fixe (le rayon) depuis le centre." },
    { level: "cm1", question: "Le cercle est :", answer: "Une ligne courbe fermée", choices: ["Une ligne courbe fermée", "Une surface plane", "Un segment", "Un polygone"], explanation: "Le cercle est la ligne courbe. La surface à l'intérieur s'appelle le disque." },
    { level: "cm2", question: "Le diamètre est-il une corde ?", answer: "Oui, c'est la plus grande corde", choices: ["Oui, c'est la plus grande corde", "Non, ce n'est pas une corde", "Oui, c'est la plus petite corde", "Seulement parfois"], explanation: "Le diamètre est une corde spéciale : c'est la plus grande corde possible car elle passe par le centre." },
    { level: "cm2", question: "Comment appelle-t-on la portion de disque délimitée par deux rayons et un arc ?", answer: "Un secteur de disque", choices: ["Un secteur de disque", "Un segment de cercle", "Un demi-cercle", "Un quart de rond"], explanation: "Le secteur de disque est la « part de gâteau » comprise entre deux rayons et un arc." },
    { level: "cm1", question: "Qu'est-ce qu'un demi-cercle ?", answer: "La moitié du cercle coupé par un diamètre", choices: ["La moitié du cercle coupé par un diamètre", "Un quart de cercle", "Un arc de 90°", "Un cercle de rayon divisé par 2"], explanation: "Le demi-cercle est la moitié du cercle, délimitée par un diamètre." },
    { level: "cm2", question: "Tous les rayons d'un même cercle sont :", answer: "De la même longueur", choices: ["De la même longueur", "De longueurs différentes", "Parallèles entre eux", "Perpendiculaires entre eux"], explanation: "Tous les rayons d'un même cercle ont la même longueur, c'est la définition du cercle." },
];
